export const translations={
 vi:{
  nav:{home:'Trang chủ',explore:'Khám phá',guides:'Hướng dẫn vẽ',gallery:'Góc tranh',quick:'Đi nhanh',themeStudio:'Phòng vẽ',themePlayful:'Vui tươi',language:'Ngôn ngữ',menu:'Menu',quickHint:'Chuyển nhanh đến chuyên mục',quickMaterials:'Chất liệu',quickMovements:'Phong cách',quickArtists:'Danh họa',top:'Lên đầu trang'},
  common:{siteDescription:'Một cuộc dạo chơi nghệ thuật của hai bố con.',galleryCTA:'Góc tranh của chúng mình ↗',footer:'Một góc nghệ thuật nhỏ của hai bố con.',copyright:'Chỉ đơn giản vì yêu hội họa.',illustration:'Hình minh họa nguyên bản của website',open:'Xem thêm ↗',source:'Nguồn và tác phẩm',try:'Thử vẽ',viewLarge:'Mở ảnh lớn ↗'},
  home:{today:'CHUYẾN DẠO CHƠI HÔM NAY',cta:'Khám phá nghệ thuật ↗',style:'Phong cách hôm nay',prev:'Tác phẩm trước',next:'Tác phẩm tiếp',pause:'Tạm dừng slideshow',resume:'Tiếp tục slideshow',illustration:'Minh họa nguyên bản',intro1:'Một góc nhỏ để ngắm, cảm nhận và sáng tạo.',intro2:'Không cần vẽ thật giỏi. Chỉ cần thấy thích.',introDesc:'Cuộc dạo chơi của hai bố con qua những bức tranh, phong cách và nét vẽ của riêng mình. Không điểm số, không áp lực — chỉ có chút bay bổng.',discover:'01 / KHÁM PHÁ',collections:'Dạo chơi qua hội họa',allCollections:'Xem mọi chuyên mục ↗',sketchTag:'TRANG SỔ TAY',sketchTitle:'Có những khoảnh khắc dành cho trang giấy.',sketchDesc:'Một ngọn núi, một góc phố, hay khuôn mặt mình muốn nhớ. Vẽ lại theo cách của mình.',sketchCTA:'Khám phá phong cảnh chì ↗',guideTag:'02 / THỬ MỘT NÉT',guideTitle:'Một vài hướng dẫn vẽ',allGuides:'Tất cả hướng dẫn ↗',openGuide:'Mở bài vẽ ↗',visualTag:'03 / SỔ VẼ NHỎ',visualTitle:'Một ghi chú, một nét vẽ',allNotes:'Tất cả infographic ↗',galleryTag:'04 / GÓC TRANH CỦA CHÚNG MÌNH',galleryTitle:'Nơi cất giữ những gì mình vẽ.',galleryDesc:'Nét chì đầu tiên, một nhân vật tự nghĩ ra hay bức phong cảnh vẽ trong buổi chiều. Không cần đánh giá. Chỉ đơn giản là thích.',galleryLink:'Ghé góc tranh ↗'},
  explore:{title:'Một thế giới hội họa nho nhỏ.',lead:'Bắt đầu từ chiếc bút chì hay hộp màu, rồi dạo chơi đến những phong cách và danh họa bạn từng nghe tên. Không cần thuộc lịch sử — chỉ cần nhìn, cảm nhận và khám phá.',materials:'Chất liệu',movements:'Phong cách',artists:'Danh họa',materialsTag:'01 / CHẤT LIỆU & DỤNG CỤ',materialsTitle:'Vẽ bằng gì nhỉ?',materialsIntro:'Từ bút chì quen thuộc đến sơn dầu, màu nước và bút vẽ kỹ thuật số. Hãy bắt đầu với dụng cụ mình đang có.',materialsLink:'Xem gợi ý ↗',materialsNote:'Chất liệu và phong cách không giống nhau: cùng một chân dung có thể vẽ bằng chì, màu nước hay trên iPad. Hình trên thẻ là minh họa chủ đề.',movementsTag:'02 / CÁCH NHÌN THẾ GIỚI',movementsTitle:'Những phong cách từng nghe qua',movementsIntro:'Phục Hưng, Ấn tượng, Hậu Ấn tượng, Lập thể và thủy mặc. Mỗi trang chỉ vài phút đọc: quan sát điều gì, vì sao thú vị và thử vẽ thế nào.',movementsNote:'Thủy mặc là truyền thống hội họa lâu dài, không phải một trào lưu cùng loại với các phong trào châu Âu. Sơn mài Việt Nam được giới thiệu riêng theo chất liệu.',artistsTag:'03 / NGƯỜI ĐỨNG SAU TÁC PHẨM',artistsTitle:'Gặp gỡ một vài danh họa',artistsIntro:'Mỗi người có một trang giới thiệu ngắn: ba điểm đáng chú ý, một tác phẩm để ngắm kỹ và một gợi ý thử vẽ.',quickTitle:'Và những cái tên có thể bạn đã nghe…',imageNote:'Hình của bảo tàng có ghi nguồn riêng. Những minh họa khác do website tạo, không phải tranh của danh họa.'},
  guides:{tag:'HƯỚNG DẪN VẼ',title1:'Cầm bút lên.',title2:'Thử xem sao nhé.',intro:'Không có giáo trình bắt buộc. Chọn thứ mình thích, xem vài bước cơ bản rồi vẽ theo cách riêng.',visualTag:'SỔ TAY BẰNG HÌNH',visualTitle:'Xem một hình, thử một nét',allNotes:'Xem toàn bộ infographic ↗',start:'BẮT ĐẦU TỪ BẤT CỨ ĐÂU',all:'Tất cả',categories:{figure:'Hình người',pencil:'Vẽ chì',landscape:'Phong cảnh',character:'Vẽ nhân vật',watercolor:'Màu nước',digital:'Vẽ trên ứng dụng'},categoryLink:'Chọn một chủ đề',open:'Mở hướng dẫn ↗',empty:'Chưa có bài hướng dẫn trong nhóm này.',note:'Hai infographic đầu tiên là sơ đồ minh họa gốc, có thể phóng to và lưu lại. Các bài khác còn dùng hình minh họa chủ đề; những bước vẽ chi tiết sẽ được bổ sung dần.',guideNote:'MỘT GHI CHÚ NHỎ',suggestedTime:'Thời gian gợi ý',supplies:'Chuẩn bị',free:'Các bước chỉ là gợi ý — cứ điều chỉnh theo nét vẽ của bạn.',back:'← Tất cả hướng dẫn',steps:'TỪNG BƯỚC MỘT',placeholder:'Ảnh trên minh họa cho chủ đề, chưa phải infographic riêng cho từng bước. Chúng ta sẽ bổ sung hình vẽ đồng nhất cho từng giai đoạn.'},
  notes:{tag:'SỔ TAY BẰNG HÌNH',title:'Một vài ghi chú bằng hình.',intro:'Hai tấm ghi chú vẽ đầu tiên về ánh sáng và dựng hình khuôn mặt. Mở lớn, lưu lại hoặc in ra để ngồi vẽ cùng nhau.',titleSingle:'GHI CHÚ BẰNG HÌNH',caption:'Minh họa giáo dục nguyên bản của G-Art Journey.',large:'Mở hình lớn ↗',download:'Lưu infographic SVG ↓',practice:'Thử vẽ',five:'NĂM BƯỚC NHO NHỎ',stepsTitle:'Cùng thử từng bước',stepsIntro:'Không cần vẽ giống hệt. Chọn một ý bạn muốn thử trên giấy hay ứng dụng vẽ.',smallNote:'Một lưu ý nhỏ',more:'Khám phá thêm hướng dẫn ↗'},
  artist:{back:'← KHÁM PHÁ / DANH HỌA',story:'MỘT CHUYỆN KỂ VỀ NGHỆ THUẬT',threeWords:'Ba từ đáng nhớ',three:'BA ĐIỀU NHỎ',interesting:'Điều gì làm tranh thú vị?',work:'MỘT TÁC PHẨM ĐỂ NGẮM',view:'Xem tác phẩm tại bảo tàng ↗',try:'THỬ MỘT NÉT',tryTitle:'Thử một nét nhỏ',guides:'Xem hướng dẫn vẽ ↗',disclaimer:'Trang giới thiệu do G-Art Journey biên soạn. Tác phẩm được liên kết tới bảo tàng. Minh họa riêng của website không phải tác phẩm của danh họa.'},
  movement:{back:'← KHÁM PHÁ / PHONG CÁCH',look:'QUAN SÁT THẾ NÀO?',recognize:'Nhận ra bằng cách nào?',clues:'Ba dấu hiệu để bắt đầu quan sát.',closer:'NGẮM KỸ HƠN',closerTitle:'Ngắm một chút nhé',try:'THỬ MỘT NÉT',tryTitle:'Thử một nét nhỏ',guides:'Xem hướng dẫn vẽ ↗',people:'NHỮNG CÁI TÊN LIÊN QUAN',artists:'Một vài họa sĩ',disclaimer:'Các phong cách chỉ là cánh cửa tìm hiểu; họa sĩ có thể thay đổi cách vẽ qua nhiều giai đoạn. Tác phẩm gốc được liên kết tới bảo tàng hoặc nguồn tham khảo.'},
  gallery:{title:'Những điều mình vẽ.',intro:'Không phải để chấm điểm. Không cần lời giải thích. Đôi khi chỉ là một bức vẽ, đơn giản vì mình thích.',filters:{all:'Tất cả',daughter:'Con gái',dad:'Bố',shared:'Hai bố con'},filterLabel:'Lọc tác phẩm',emptyFilter:'Chưa có tác phẩm trong nhóm này.',emptyTag:'TRANG GIẤY TRẮNG. MỘT KHỞI ĐẦU MỚI.',emptyTitle:'Bức tranh đầu tiên đang chờ.',emptyIntro:'Gallery đang chờ bức tranh đầu tiên. Đưa ảnh vào thư mục GitHub của hai bố con; website sẽ tự nhận khi cập nhật.',folder:'Mở thư mục ảnh trên GitHub ↗',warning:'Lưu ý: gallery và hình trong repository Public đều được công khai. Chỉ đưa lên tác phẩm hai bố con đồng ý chia sẻ; tránh ảnh có thông tin cá nhân.',openImage:'Mở ảnh lớn',owners:{dad:'Bố',daughter:'Con gái',shared:'Hai bố con'}},
  quick:{label:'Đi nhanh đến mục',go:'Chuyển tới',sections:'Trong trang này'}
 },
 en:{
  nav:{home:'Home',explore:'Explore Art',guides:'Drawing Guides',gallery:'Our Gallery',quick:'Quick Explore',themeStudio:'Studio',themePlayful:'Playful',language:'Language',menu:'Menu',quickHint:'Jump to an art collection',quickMaterials:'Materials',quickMovements:'Styles',quickArtists:'Artists',top:'Back to top'},
  common:{siteDescription:'A little art journey for a father and daughter.',galleryCTA:'Our little gallery ↗',footer:'A little art space for father and daughter.',copyright:'Created simply for the joy of art.',illustration:'Original site illustration',open:'Explore ↗',source:'Artwork & source',try:'Try it',viewLarge:'View full image ↗'},
  home:{today:'TODAY’S ART JOURNEY',cta:'Wander through art ↗',style:"Today's style",prev:'Previous artwork',next:'Next artwork',pause:'Pause slideshow',resume:'Resume slideshow',illustration:'Original site illustration',intro1:'A little space to see, feel and create.',intro2:'No need to be perfect. Just enjoy making art.',introDesc:'A father and daughter wandering through paintings, styles and their own sketches. No scores, no pressure — just a little imagination.',discover:'01 / DISCOVER',collections:'Wander through art',allCollections:'Explore all collections ↗',sketchTag:'FROM OUR SKETCHBOOK',sketchTitle:'Some moments belong on paper.',sketchDesc:'A mountain, a little street, or a face worth remembering. Draw it in your own way.',sketchCTA:'Explore pencil landscapes ↗',guideTag:'02 / TRY SOMETHING',guideTitle:'A few drawing guides',allGuides:'All guides ↗',openGuide:'Open guide ↗',visualTag:'03 / LITTLE SKETCHBOOK',visualTitle:'A little note, a little drawing',allNotes:'All visual notes ↗',galleryTag:'04 / OUR LITTLE GALLERY',galleryTitle:'A place for the things we make.',galleryDesc:'A first pencil sketch, an imagined character, or a landscape made one afternoon. No judging — simply because we like it.',galleryLink:'Visit our gallery ↗'},
  explore:{title:'A little world of art.',lead:'Start with a pencil or a box of paints, then wander through styles and artists you might recognize. No history exam — just look, feel and explore.',materials:'Materials',movements:'Styles',artists:'Artists',materialsTag:'01 / MATERIALS & TOOLS',materialsTitle:'What shall we draw with?',materialsIntro:'From familiar pencils to oils, watercolor and digital brushes. Begin with the tools already at hand.',materialsLink:'Explore ideas ↗',materialsNote:'A medium and a style are different: the same portrait can be made in graphite, watercolor or on an iPad. Card images are topic illustrations.',movementsTag:'02 / WAYS OF SEEING',movementsTitle:'A few familiar art styles',movementsIntro:'Renaissance, Impressionism, Post-Impressionism, Cubism and ink wash. Each page is a quick look at what to notice and a small drawing idea.',movementsNote:'Ink wash is a long-lived artistic tradition, not the same category as a European movement. Vietnamese lacquer is introduced as its own medium and tradition.',artistsTag:'03 / PEOPLE BEHIND THE ART',artistsTitle:'Meet a few artists',artistsIntro:'One short illustrated profile each: three things to notice, an artwork to explore and an optional sketch idea.',quickTitle:'And a few other names you may know…',imageNote:'Museum images carry separate credits. Other illustrations were made for this site and are not works by the named artists.'},
  guides:{tag:'DRAWING GUIDES',title1:'Pick up a pencil.',title2:'See what happens.',intro:'No required course. Pick something you like, read a few basics and draw in your own way.',visualTag:'VISUAL NOTES',visualTitle:'Look at a picture, try a line',allNotes:'All visual notes ↗',start:'START ANYWHERE',all:'All',categories:{figure:'Figure Drawing',pencil:'Pencil Art',landscape:'Landscape',character:'Character Art',watercolor:'Watercolor',digital:'Digital Art'},categoryLink:'Choose a topic',open:'Open guide ↗',empty:'No guides in this collection yet.',note:'The first two original diagram notes can be enlarged and saved. Other guides still use topic illustrations; consistent step-by-step artwork will be added over time.',guideNote:'A LITTLE NOTE',suggestedTime:'Suggested time',supplies:'Supplies',free:'These steps are suggestions — adapt them to your own drawing.',back:'← All guides',steps:'STEP BY STEP',placeholder:'The picture above illustrates the subject rather than every drawing step. Consistent step images will be added later.'},
  notes:{tag:'VISUAL SKETCHBOOK',title:'A few visual notes.',intro:'Our first two visual notes explore light and head construction. View them large, save or print them, then draw together.',titleSingle:'VISUAL NOTE',caption:'Original educational illustration by G-Art Journey.',large:'View large ↗',download:'Save SVG infographic ↓',practice:'Try it',five:'FIVE LITTLE STEPS',stepsTitle:'Try it step by step',stepsIntro:'It need not look identical. Choose one idea to try on paper or in a drawing app.',smallNote:'A little note',more:'Explore more guides ↗'},
  artist:{back:'← EXPLORE ART / ARTISTS',story:'A LITTLE ART STORY',threeWords:'Three words to remember',three:'THREE LITTLE THINGS',interesting:'What makes this art interesting?',work:'ONE WORK TO SEE',view:'View at the museum ↗',try:'TRY IT YOURSELF',tryTitle:'Try a small sketch',guides:'Drawing guides ↗',disclaimer:'This profile is written by G-Art Journey. Original works link to museums. Site illustrations are not attributed to the artist.'},
  movement:{back:'← EXPLORE ART / STYLES',look:'HOW TO LOOK',recognize:'How can you spot it?',clues:'Three things to start noticing.',closer:'LOOK CLOSER',closerTitle:'Take a closer look',try:'TRY IT YOURSELF',tryTitle:'Try a small sketch',guides:'Drawing guides ↗',people:'SOME NAMES TO KNOW',artists:'A few artists',disclaimer:'These labels are a starting point; an artist’s approach may change over time. Original artworks link to museums or referenced sources.'},
  gallery:{title:'The things we make.',intro:'Not for scoring. No explanation needed. Sometimes a drawing is simply something we enjoy.',filters:{all:'All artworks',daughter:'Daughter',dad:'Dad',shared:'Together'},filterLabel:'Filter artworks',emptyFilter:'No artworks in this group yet.',emptyTag:'A BLANK PAGE. A NEW BEGINNING.',emptyTitle:'Your first artwork belongs here.',emptyIntro:'Our little gallery is waiting for its first picture. Add an image to the family folders on GitHub; the site will update on the next build.',folder:'Open artwork folder on GitHub ↗',warning:'This gallery and images in the public repository are publicly visible. Only share artwork both of you are happy to publish, and avoid personal information.',openImage:'View full artwork',owners:{dad:'Dad',daughter:'Daughter',shared:'Together'}},
  quick:{label:'Jump to section',go:'Go to',sections:'On this page'}
 }
};
export const language = value => value==='vi'?'vi':'en';
export const ui = value => translations[language(value)];
export const sitePath=(value,path='')=> '/G-Art-Journey/'+(language(value)==='en'?'en/':'')+path;
