import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const ABS=relative=>path.resolve(root,relative);
const sha256=bytes=>createHash('sha256').update(bytes).digest('hex');
const fail=message=>{throw new Error(message);};
const safePart=value=>typeof value==='string'&&/^[a-z][a-z0-9-]*$/.test(value);
const safePath=relative=>{
 if(typeof relative!=='string'||path.isAbsolute(relative)||relative.split(/[\\/]/).some(x=>x==='..'||x===''))fail('Unsafe path: '+relative);
 return ABS(relative);
};
export function validateManifest(m){
 if(!safePart(m.batchId)||!Array.isArray(m.items)||m.items.length<1||m.items.length>20)fail('Invalid batch manifest');
 if(!/^public\/infographics\/[a-z][a-z0-9-]*$/.test(m.outputDir))fail('Invalid output directory');
 const ids=new Set();
 for(const item of m.items){
  if(!safePart(item.slug)||item.filename!==item.slug+'.webp'||item.sourceName!==item.slug+'.png'||ids.has(item.slug))fail('Unsafe or duplicate batch item: '+item.slug);
  ids.add(item.slug);
 }
 return m;
}
export async function loadManifest(relative){
 const manifest=JSON.parse(await readFile(safePath(relative),'utf8'));
 return validateManifest(manifest);
}
const getOutputPath=(m,item)=>safePath(m.outputDir+'/'+item.filename);
async function inspectImage(sharp,buffer,filename){
 if(buffer.toString('ascii',0,4)!=='RIFF'||buffer.toString('ascii',8,12)!=='WEBP')fail('Invalid WebP header: '+filename);
 const meta=await sharp(buffer,{failOn:'error'}).metadata();
 if(meta.format!=='webp'||!meta.width||!meta.height||Math.min(meta.width,meta.height)<600)fail('Invalid WebP dimensions: '+filename);
 return meta;
}
export async function verify(m,sharp){
 const outputs=[];
 for(const item of m.items){
  const file=getOutputPath(m,item);
  let bytes;
  try{bytes=await readFile(file);}catch{fail('Missing approved poster: '+file);}
  const meta=await inspectImage(sharp,bytes,item.filename);
  const size=bytes.length;
  if(size>5*1024*1024)fail('Unusually large poster requires manual review: '+item.filename);
  outputs.push({slug:item.slug,path:m.outputDir+'/'+item.filename,bytes:size,width:meta.width,height:meta.height,sha256:sha256(bytes)});
 }
 return outputs;
}
export async function prepare(m,inputDir,sharp){
 if(!inputDir)fail('Provide --input pointing to the source art folder');
 await mkdir(safePath(m.outputDir),{recursive:true});
 const results=[];
 for(const item of m.items){
  const source=path.resolve(inputDir,item.sourceName);
  // A .webp source with the same slug is also supported.
  let sourceFile=source;
  try{await stat(sourceFile);}catch{sourceFile=source.replace(/\.png$/i,'.webp');}
  let image;
  try{image=sharp(sourceFile,{failOn:'error',limitInputPixels:80000000}).rotate();await image.metadata();}
  catch{fail('Missing or unreadable source image: '+item.sourceName);}
  const bytes=await image.resize({width:m.maxLongEdge||1600,height:m.maxLongEdge||1600,fit:'inside',withoutEnlargement:true})
    .flatten({background:'#fffaf5'}).webp({quality:87,effort:5}).toBuffer();
  const meta=await inspectImage(sharp,bytes,item.filename);
  if(Math.min(meta.width,meta.height)<(m.minShortEdge||600))fail('Poster resolution too small: '+item.slug);
  const dest=getOutputPath(m,item);
  await writeFile(dest,bytes);
  results.push({slug:item.slug,path:m.outputDir+'/'+item.filename,bytes:bytes.length,width:meta.width,height:meta.height,sha256:sha256(bytes)});
  console.log(item.slug+': '+meta.width+'×'+meta.height+', '+Math.ceil(bytes.length/1024)+' KiB'+(bytes.length>(m.preferredMaxBytes||1048576)?' [soft size warning]':''));
 }
 return results;
}
function manifestJS(records){
 return '// Generated by npm run art:prepare; do not edit checksums by hand.\nexport const characterAssets = '+JSON.stringify(records,null,2)+';\n';
}
export async function activate(m,records){
 if(m.batchId!=='character-02')fail('Unsupported activation target: '+m.batchId);
 if(records.length!==m.items.length)fail('Cannot activate incomplete batch');
 const contentPath=ABS('src/data/content.mjs');
 let content=await readFile(contentPath,'utf8');
 const imp="import { characterGuides } from './character-guides.mjs';";
 if(!content.includes(imp)){
  const anchor="import { humanGuides } from './human-guides.mjs';";
  if(!content.includes(anchor))fail('Import anchor has changed; review the application before activating');
  content=content.replace(anchor,anchor+'\n'+imp);
 }
 if(!content.includes('...characterGuides')){
  const anchor='...practiceGuides, ...humanGuides';
  if(!content.includes(anchor))fail('Guide-list anchor has changed; review before activating');
  content=content.replace(anchor,anchor+', ...characterGuides');
 }
 await writeFile(ABS('src/data/character-assets.mjs'),manifestJS(records));
 await writeFile(contentPath,content);
 console.log('Activated '+records.length+' complete character guides. Commit only optimized WebP files.');
}
export async function main(args=process.argv.slice(2)){
 const opt={manifest:'assets/batches/character-02.json'};
 for(let i=0;i<args.length;i++){
  const token=args[i];
  if(token==='--manifest'||token==='--input')opt[token.slice(2)]=args[++i];
  else if(token==='--activate'||token==='--check')opt[token.slice(2)]=true;
  else fail('Unknown argument: '+token);
 }
 const m=await loadManifest(opt.manifest);
 const {default:sharp}=await import('sharp');
 if(!opt.check&&opt.input)await prepare(m,opt.input,sharp);
 const records=await verify(m,sharp);
 const total=records.reduce((sum,x)=>sum+x.bytes,0);
 console.log('Verified '+records.length+' complete WebP posters; '+(total/1048576).toFixed(2)+' MiB total.');
 if(opt.activate)await activate(m,records);
 return records;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){
 main().catch(err=>{console.error(err.message);process.exitCode=1;});
}
